// 本地菜单图标配置
// 使用 Element Plus Icons 替代原 iconify 图标
import {
  Menu,
  Edit,
  Guide,
  SetUp,
  Monitor,
  Lollipop,
  Histogram,
  HomeFilled,
  Search,
  Setting,
  User,
  Document,
  Files,
  FolderOpened,
  Link,
  List,
  Grid,
  DataAnalysis,
  TrendCharts,
  PieChart,
  Calendar,
  Clock,
  Bell,
  Message,
  ChatDotRound,
  InfoFilled,
  WarningFilled,
  CircleCheckFilled,
  CircleCloseFilled,
  QuestionFilled,
  Plus,
  Minus,
  Close,
  Check,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Refresh,
  Delete,
  EditPen,
  View,
  Hide,
  Download,
  Upload,
  Printer,
  Share,
  Star,
  Collection,
  Tools,
  Operation,
  MoreFilled
} from "@element-plus/icons-vue";
import type { Component } from "vue";

// 图标名称到组件的映射表
// 键名格式与原 iconify 保持一致，便于菜单配置兼容
export const iconMap: Record<string, Component> = {
  // Element Plus 图标（ep/ 前缀）
  "ep/menu": Menu,
  "ep/edit": Edit,
  "ep/guide": Guide,
  "ep/set-up": SetUp,
  "ep/monitor": Monitor,
  "ep/lollipop": Lollipop,
  "ep/histogram": Histogram,
  "ep/home-filled": HomeFilled,
  "ep/search": Search,
  "ep/setting": Setting,
  "ep/user": User,
  "ep/document": Document,
  "ep/files": Files,
  "ep/folder-opened": FolderOpened,
  "ep/link": Link,
  "ep/list": List,
  "ep/grid": Grid,
  "ep/data-analysis": DataAnalysis,
  "ep/trend-charts": TrendCharts,
  "ep/pie-chart": PieChart,
  "ep/calendar": Calendar,
  "ep/clock": Clock,
  "ep/bell": Bell,
  "ep/message": Message,
  "ep/chat-dot-round": ChatDotRound,
  "ep/info-filled": InfoFilled,
  "ep/warning-filled": WarningFilled,
  "ep/circle-check-filled": CircleCheckFilled,
  "ep/circle-close-filled": CircleCloseFilled,
  "ep/question-filled": QuestionFilled,
  "ep/plus": Plus,
  "ep/minus": Minus,
  "ep/close": Close,
  "ep/check": Check,
  "ep/arrow-up": ArrowUp,
  "ep/arrow-down": ArrowDown,
  "ep/arrow-left": ArrowLeft,
  "ep/arrow-right": ArrowRight,
  "ep/refresh": Refresh,
  "ep/delete": Delete,
  "ep/edit-pen": EditPen,
  "ep/view": View,
  "ep/hide": Hide,
  "ep/download": Download,
  "ep/upload": Upload,
  "ep/printer": Printer,
  "ep/share": Share,
  "ep/star": Star,
  "ep/collection": Collection,
  "ep/tools": Tools,
  "ep/operation": Operation,
  "ep/more-filled": MoreFilled,

  // Remix Icon 兼容映射（映射到相似的 Element Plus 图标）
  "ri/mind-map": Grid,
  "ri/admin-fill": User,
  "ri/table-line": List,
  "ri/links-fill": Link,
  "ri/admin-line": User,
  "ri/list-check": List,
  "ri/search-line": Search,
  "ri/window-line": Monitor,
  "ri/ubuntu-fill": Monitor,
  "ri/history-fill": Clock,
  "ri/edit-box-line": Edit,
  "ri/code-box-line": Document,
  "ri/artboard-line": Grid,
  "ri/markdown-line": Document,
  "ri/file-info-line": Document,
  "ri/bank-card-line": Collection,
  "ri/file-ppt-2-line": Files,
  "ri/git-branch-line": Share,
  "ri/settings-3-line": Setting,
  "ri/user-voice-line": User,
  "ri/bookmark-2-line": Collection,
  "ri/file-search-line": Search,
  "ri/chat-search-line": Search,
  "ri/information-line": InfoFilled,
  "ri/terminal-window-line": Monitor,
  "ri/checkbox-circle-line": CircleCheckFilled,
  "ri/bar-chart-horizontal-line": DataAnalysis
};

/**
 * 根据图标名称获取对应的组件
 * @param name 图标名称，如 "ep/menu" 或 "ri/admin-fill"
 * @returns 图标组件或 undefined
 */
export function getIconComponent(name: string): Component | undefined {
  return iconMap[name];
}

/**
 * 检查图标名称是否在映射表中
 * @param name 图标名称
 * @returns 是否存在
 */
export function hasIcon(name: string): boolean {
  return name in iconMap;
}

// 导出所有图标组件，便于直接使用
export {
  Menu,
  Edit,
  Guide,
  SetUp,
  Monitor,
  Lollipop,
  Histogram,
  HomeFilled,
  Search,
  Setting,
  User,
  Document,
  Files,
  FolderOpened,
  Link,
  List,
  Grid,
  DataAnalysis,
  TrendCharts,
  PieChart,
  Calendar,
  Clock,
  Bell,
  Message,
  ChatDotRound,
  InfoFilled,
  WarningFilled,
  CircleCheckFilled,
  CircleCloseFilled,
  QuestionFilled,
  Plus,
  Minus,
  Close,
  Check,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Refresh,
  Delete,
  EditPen,
  View,
  Hide,
  Download,
  Upload,
  Printer,
  Share,
  Star,
  Collection,
  Tools,
  Operation,
  MoreFilled
};
